language: java
jdk: oraclejdk8
install: true

addons:
  postgresql: "10"

script:
  - mvn test -T8 -DskipTests=false -Ddb.config.location=environment -Dtest.db.type=POSTGRESQL -Dtest.db.url=jdbc:postgresql://localhost:5432/cts_tests_schema -Dtest.db.username=postgres -Pcreate-tests-schema,drop-tests-schema,postgresql,jacoco-coverage
  - mvn spotbugs:check -T8