sudo: required
install: true
language: java
jdk: oraclejdk8

services:
- postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
  global:
  - PGPORT=5433
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
  - ORACLE_SID=XE

before_install:


# POSTGRESQL DB
#- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
#- sudo service postgresql restart

# ORACLE DB
- sudo wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
- sudo bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh

# WAIT
- sleep 2

before_script:
- psql -c 'CREATE DATABASE cts_tests_schema;' -U postgres

jobs:
  include:
  - stage: test
    script:
    - mvn test -e -T8 -DskipTests=false -Ddb.config.location=environment -Dtests.db.type=POSTGRESQL -Dtests.db.url=jdbc:postgresql://localhost:5433/cts_tests_schema -Dtests.db.username=postgres -Ppostgresql,jacoco-coverage
    - mvn spotbugs:check -T8

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2
