sudo: true
install: true
language: java
jdk: oraclejdk8

services:
- postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10

env:
  global:
  - PGPORT=5433

before_install:
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sleep 1

jobs:
  include:
  - stage: test
    script:
    - mvn test -T8 -DskipTests=false -Ddb.config.location=environment -Dtests.db.type=POSTGRESQL -Dtests.db.url=jdbc:postgresql://localhost:5433/cts_tests_schema -Dtests.db.username=postgres -Pcreate-tests-schema,drop-tests-schema,postgresql,jacoco-coverage
    - mvn spotbugs:check -T8

cache:
  directories:
  - $HOME/.m2
