language: java
jdk: oraclejdk8
install: true

addons:
  postgresql: "10"

cache:
  directories:
  - $HOME/.m2

script:
- mvn test -T8 -DskipTests=false -Ddb.config.location=environment -Dtests.db.type=POSTGRESQL -Dtests.db.url=jdbc:postgresql://localhost:5433/cts_tests_schema -Dtests.db.username=postgres -Pcreate-tests-schema,drop-tests-schema,postgresql,jacoco-coverage
- mvn spotbugs:check -T8